---
# ref: https://taskfile.dev/

version: "3"

vars:
  TF_PATH: terraform/__modules

tasks:
  lint:
    description: python linters
    cmds:
      - black . --line-length 119
      - flake8 . --max-line-length 119 --statistics  --extend-exclude venv,dist
      - yamllint . -c .yamllint.yml

  common:
    description: extra things
    cmds:
      - typer --install-completion

  docs:
    cmds:
      # ref: https://typer.tiangolo.com/typer-cli/#generate-docs-with-typer-cli
      # poetry shell # activate venv
      # poetry install # install python packages, especially typer-cli
      - typer horbach_cli.main utils docs --output horbach_cli/README.md --name h-cli
