---

name: lint

on: [push, pull_request]

jobs:

  black:
    name: black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --line-length 119"

  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: flake8
        run: flake8 . --max-line-length 119 --statistics

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: yamllint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: .
          yamllint_config_filepath: hacks/.yamllint.yml
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
